set termout on
set head off
set pause off
set linesize 132  

spool /SiGEPAPP/LogCriacaoBanco.log

@ /SiGEPAPP/APPP_CREATE_USERS.sql                                                                                                  

@ /SiGEPAPP/APPP_TB_USER.SQL

@ /SiGEPAPP/APPP_TB_LOGIN.SQL

@ /SiGEPAPP/APPP_TB_USER_EMAIL.SQL

@ /SiGEPAPP/APPP_TB_USER_TELEFONE.SQL

@ /SiGEPAPP/APPP_TB_CIDADE.SQL

@ /SiGEPAPP/APPP_TB_ESTADO.SQL

@ /SiGEPAPP/APPP_TB_CODIGO_POSTAL.SQL

@ /SiGEPAPP/APPP_TB_USER_ENDERECO.SQL

@ /SiGEPAPP/APPP_TB_ESTRUT_OBJ.SQL

@ /SiGEPAPP/APPP_TB_OBJETO.SQL

@ /SiGEPAPP/APPP_TB_PATTERN.SQL

@ /SiGEPAPP/APPP_TB_ANTI_PATTERN.SQL

@ /SiGEPAPP/APPP_TB_PERSONA.SQL

@ /SiGEPAPP/APPP_TB_OBJ_RELAC.SQL

@ /SiGEPAPP/APPP_TB_TIPO.SQL

@ /SiGEPAPP/APPP_TB_ATRIBUTO_OBJ.SQL

@ /SiGEPAPP/APPP_TB_RELAC_ATRIB.SQL

@ /SiGEPAPP/APPP_TB_QUESTIONARIO.SQL

@ /SiGEPAPP/APPP_TB_PERGUNTA.SQL

@ /SiGEPAPP/APPP_TB_RESPOSTA.SQL

@ /SiGEPAPP/APPP_TB_PERGUNTA_QUEST.SQL

@ /SiGEPAPP/APPP_TB_RESPOSTA_PERGUNTA.SQL

SPOOL OFF

/
