set termout on
set head off
set linesize 132  

spool /SiGEPAPP/Arquivos/Procedures/LogProcedures.log

@ /SiGEPAPP/Arquivos/Procedures/APPP_PKG_VETORES.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_CRIA_TABELA_ESTRUT.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_ANTI_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_ATRIBUTO_OBJ.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_ATRIB_ESTRUTURA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_CIDADE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_CODIGO_POSTAL.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_ESTADO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_ESTRUT_OBJ.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_LOGIN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_OBJETO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_OBJ_RELAC.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_PERGUNTA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_RESP_QUEST_PREENCH.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_PERSONA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_QUEST_PREENCH.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_ESTRUT_QUEST.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_RESPOSTA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_RELAC_PERG_RESP.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_TIPO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_USER.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_USER_EMAIL.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_USER_ENDERECO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_USER_TELEFONE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_ANTI_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_ATRIBUTO_OBJ.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_ATRIB_ESTRUTURA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_CIDADE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_CODIGO_POSTAL.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_ESTADO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_ESTRUT_OBJ.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_LOGIN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_OBJETO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_OBJ_RELAC.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_PERGUNTA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_RESP_QUEST_PREENCH.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_PERSONA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_QUEST_PREENCH.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_RESPOSTA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_RELAC_PERG_RESP.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_ESTRUT_QUEST.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_TB_LOGIN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_TIPO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_USER.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_USER_EMAIL.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_USER_ENDERECO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_USER_TELEFONE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_PES_ATRIB_POR_ESTRUT.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_ANTI_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_ATRIBUTO_OBJ.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_ATRIB_ESTRUTURA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_CIDADE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_CODIGO_POSTAL.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_ESTADO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_ESTRUT_OBJ.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_EXISTE_LOGIN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_LOGIN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_OBJETO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_OBJ_RELAC.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_PERGUNTA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_RESP_QUEST_PREENCH.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_PERSONA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_QUEST_PREENCH.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_RESPOSTA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_RELAC_PERG_RESP.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_ESTRUT_QUEST.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_TIPO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_USERS.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_USER_EMAIL.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_USER_ENDERECO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_USER_TELEFONE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_ANTI_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_ATRIBUTO_OBJ.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_ATRIB_ESTRUTURA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_CIDADE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_ESTADO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_ESTRUT_OBJ.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_LOGIN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_OBJETO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_OBJ_RELAC.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_PERGUNTA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_RESP_QUEST_PREENCH.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_PERSONA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_QUEST_PREENCH.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_RESPOSTA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_RELAC_PERG_RESP.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_ESTRUT_QUEST.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_TIPO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_USER.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_USER_EMAIL.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_USER_ENDERECO.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_USER_TELEFONE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_PES_PARAM_PROCEDURE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_PKG_VETORES.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_EXEC_MANIP_GENERICA.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_OBJ_SIMILARES.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_INS_AVAL_OBJ_USER.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_AVAL_OBJ_USER.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_UPD_AVAL_OBJ_USER.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_DEL_AVAL_OBJ_USER.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_CREATE_PATTERN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_APPP_GEN.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_APP_GERAL.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_APP_SIMILARIDADE.sql
@ /SiGEPAPP/Arquivos/Procedures/APPP_SEL_PE_SIMILARIDADE.sql

SPOOL OFF

/
