set termout on
set head off
set linesize 132  

spool /SiGEPAPP/Arquivos/ScriptsDrop/LogDropBanco.log

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_RESP_QUEST_PREENCH.sql 

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_QUEST_PREENCH.sql   

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_RELAC_QUEST_OBJ.sql 

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_RELAC_PERG_RESP.SQL 

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ESTRUT_QUEST.sql 

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_RESPOSTA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_PERGUNTA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ATRIB_ESTRUTURA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_RELAC_ATRIB.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ATRIB_ESTRUTURA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ATRIBUTO_OBJ.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_TIPO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_OBJ_RELAC.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_PERSONA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ANTI_PATTERN.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_PATTERN.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_OBJETO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ESTRUT_OBJ.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_USER_ENDERECO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_CODIGO_POSTAL.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_CIDADE.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ESTADO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_USER_TELEFONE.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_USER_EMAIL.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_LOGIN.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_USER.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/01-DROP_CREATED_TABLES.sql                                                                                                

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_CREATE_USERS.sql 

SPOOL OFF



/
