set termout on
set head off
set linesize 132  

spool /SiGEPAPP/Arquivos/ScriptsDrop/LogDropBanco.log

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_RESPOSTA_PERGUNTA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_PERGUNTA_QUEST.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_RESPOSTA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_PERGUNTA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ATRIB_ESTRUTURA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_QUESTIONARIO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_RELAC_ATRIB.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ATRIB_ESTRUTURA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ATRIBUTO_OBJ.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_TIPO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_OBJ_RELAC.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_PERSONA.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ANTI_PATTERN.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_PATTERN.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_OBJETO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ESTRUT_OBJ.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_USER_ENDERECO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_CODIGO_POSTAL.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_CIDADE.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_ESTADO.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_USER_TELEFONE.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_USER_EMAIL.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_LOGIN.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_TB_USER.SQL

@ /SiGEPAPP/Arquivos/ScriptsDrop/DROP_APPP_CREATE_USERS.sql  

@ /SiGEPAPP/Arquivos/ScriptsDrop/01-DROP_CREATED_TABLES.sql                                                                                                

SPOOL OFF



/
