/**********************************************************************************************************************
* Project Name           : SiGEPAPP
* APPP_TB_ESTRUT_OBJ.SQL : Script para drop da tabela APPP_TB_ESTRUT_OBJ
* Author                 : WeeDo 
* History                : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a sequence APPP_SEQ_ESTRUT_OBJ' FROM DUAL;
drop sequence APPP_SEQ_ESTRUT_OBJ;

SELECT 'Dropando a tabela APPP_TB_ESTRUT_OBJ' FROM DUAL;
drop table APPP_TB_ESTRUT_OBJ;
/
