/**********************************************************************************************************************
* Project Name              : SiGEPAPP
* APPP_TB_QUEST_PREENCH.SQL : Script para drop da tabela APPP_TB_QUEST_PREENCH
* Author                    : WeeDo 
* History                   : 24/03/2009 - Matheus Goncalves
*							: 24/04/2009 - Guilherme Wachs Lopes: Drop sequence
***********************************************************************************************************************/

drop sequence APPP_SEQ_QUEST_PREE;

drop table APPP_TB_QUEST_PREENCH;

/
