/**********************************************************************************************************************
* Project Name                : SiGEPAPP
* APPP_TB_ATRIB_ESTRUTURA.SQL : Script para drop da tabela APPP_TB_ATRIB_ESTRUTURA
* Author                      : WeeDo 
* History                     : 06/03/2009 - Matheus Gonçalves - Versão Inicial
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_ATRIB_ESTRUTURA' FROM DUAL;
Drop table APPP_TB_ATRIB_ESTRUTURA;
 
/

