/**********************************************************************************************************************
* Project Name                   : SiGEPAPP
* APPP_TB_RESPOSTA_PERGUNTA.SQL  : Script para drop da tabela APPP_TB_RESPOSTA_PERGUNTA
* Author                         : WeeDo 
* History                        : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_RESPOSTA_PERGUNTA' FROM DUAL;

drop table APPP_TB_RESPOSTA_PERGUNTA;

/
