/**********************************************************************************************************************
* Project Name       : SiGEPAPP
* APPP_TB_OBJETO.SQL : Script para drop da tabela APPP_TB_OBJETO
* Author             : WeeDo 
* History            : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a sequece APPP_SEQ_OBJETO' FROM DUAL;
drop sequence APPP_SEQ_OBJETO;

SELECT 'Dropando a tabela APPP_TB_OBJETO' FROM DUAL;
drop table APPP_TB_OBJETO;

/
