/**********************************************************************************************************************
* Project Name           : SiGEPAPP
* APPP_TB_OBJ_RELAC.SQL  : Script para drop da tabela APPP_TB_OBJ_RELAC
* Author                 : WeeDo 
* History                : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_OBJ_RELAC' FROM DUAL;
drop table APPP_TB_OBJ_RELAC;


/
