/**********************************************************************************************************************
* Project Name                : SiGEPAPP
* APPP_TB_PERGUNTA_QUEST.SQL  : Script para drop da tabela APPP_TB_PERGUNTA_QUEST
* Author                      : WeeDo 
* History                     : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_PERGUNTA_QUEST' FROM DUAL;
drop table APPP_TB_PERGUNTA_QUEST;
/
