/**********************************************************************************************************************
* Project Name             : SiGEPAPP
* APPP_TB_RELAC_ATRIB.SQL  : Script para drop da tabela APPP_TB_RELAC_ATRIB
* Author                   : WeeDo 
* History                  : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a sequence APPP_SEQ_RELAC_ATRIB' FROM DUAL;
drop sequence APPP_SEQ_RELAC_ATRIB;

SELECT 'Dropando a tabela APPP_TB_RELAC_ATRIB' FROM DUAL;
drop table APPP_TB_RELAC_ATRIB;

/

