/**********************************************************************************************************************
* Project Name             : SiGEPAPP
* APPP_TB_QUESTIONARIO.SQL : Script para drop da tabela APPP_TB_QUESTIONARIO
* Author                   : WeeDo 
* History                  : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a sequence APPP_SEQ_QUESTIONARIO' FROM DUAL;
drop sequence APPP_SEQ_QUESTIONARIO;

SELECT 'Dropando a tabela APPP_TB_QUESTIONARIO' FROM DUAL;
drop table APPP_TB_QUESTIONARIO;

/
