REM INSERTING into APPP_TB_ESTRUT_OBJ

Insert into APPP_TB_ESTRUT_OBJ (CD_USER,DS_ESTRUTURA,DT_CRIACAO,NM_ESTRUTURA,NM_TB_ESTRUT,TP_ESTRUTURA) 
										values (35140189879,'Pattern Default',to_timestamp('17/03/09','DD/MM/RR HH24:MI:SSXFF'),'Pattern','APPP_TB_PATTERN','PA');

Insert into APPP_TB_ESTRUT_OBJ (CD_USER,DS_ESTRUTURA,DT_CRIACAO,NM_ESTRUTURA,NM_TB_ESTRUT,TP_ESTRUTURA) 
										values (35140189879,'Anti-Pattern Default',to_timestamp('17/03/09','DD/MM/RR HH24:MI:SSXFF'),'Anti-Pattern','APPP_TB_ANTI_PATTERN','AP');

Insert into APPP_TB_ESTRUT_OBJ (CD_USER,DS_ESTRUTURA,DT_CRIACAO,NM_ESTRUTURA,NM_TB_ESTRUT,TP_ESTRUTURA) 
										values (35140189879,'Persona Default',to_timestamp('17/03/09','DD/MM/RR HH24:MI:SSXFF'),'Persona','APPP_TB_PERSONA','PE');
