Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (78,1,'Descrição - blablablabla','S','Descrição');
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (81,1,'Os sintomas do problema','S','Sintomas');
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (82,1,'Consequencias','S','Consequências');
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (90,3,'Data para entrega do código','S','Data de entrega');
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (91,3,null,'S','Data de saida');
