REM INSERTING into APPP_TB_ATRIBUTO_OBJ
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,DS_TAM_ATRIB,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (78.501.'Descição - blablablabla'.'1'.'S'.'Descrição');
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,DS_TAM_ATRIB,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (81.501.'Os sintomas do problema'.'1'.'S'.'Sintomas');
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,DS_TAM_ATRIB,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (82.501.'Consequencias'.'1'.'S'.'Consequências');
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,DS_TAM_ATRIB,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (90.524.'Data para entrega do código'.'1'.'S'.'Data de entrega');
Insert into APPP_TB_ATRIBUTO_OBJ (CD_ATRIBUTO_OBJ,CD_TIPO,DS_ATRIBUTO_OBJ,DS_TAM_ATRIB,FL_ATRIB_RELAC,NM_ATRIBUTO_OBJ) values (91.524.null.'2'.'S'.'Data de saida');
