/**********************************************************************************************************************
* Project Name       : SiGEPAPP
* APPP_TB_CIDADE.SQL : Script para drop da tabela APPP_TB_CIDADE
* Author             : WeeDo 
* History            : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_CIDADE' FROM DUAL;
drop table APPP_TB_CIDADE;

/
