/**********************************************************************************************************************
* Project Name              : SiGEPAPP
* APPP_TB_USER_TELEFONE.SQL : Script para drop da tabela APPP_TB_USER_TELEFONE
* Author                    : WeeDo 
* History                   : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_USER_TELEFONE' FROM DUAL;
drop table APPP_TB_USER_TELEFONE;

/
