/**********************************************************************************************************************
* Project Name         : SiGEPAPP
* APPP_TB_PERGUNTA.SQL : Script para drop da tabela APPP_TB_PERGUNTA
* Author               : WeeDo 
* History              : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a sequence APPP_SEQ_PERGUNTA' FROM DUAL;
drop sequence APPP_SEQ_PERGUNTA;

SELECT 'Dropando a tabela APPP_TB_PERGUNTA' FROM DUAL;
drop table APPP_TB_PERGUNTA;
 
/
