/**********************************************************************************************************************
* Project Name     : SiGEPAPP
* APPP_TB_TIPO.SQL : Script para drop da tabela APPP_TB_TIPO
* Author           : WeeDo 
* History          : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a sequence APPP_SEQ_TIPO' FROM DUAL;
drop sequence APPP_SEQ_TIPO;

SELECT 'Dropando a tabela APPP_TB_TIPO' FROM DUAL;
drop table APPP_TB_TIPO;

/
