/**********************************************************************************************************************
* Project Name        : SiGEPAPP
* APPP_TB_PERSONA.SQL : Script para drop da tabela APPP_TB_PERSONA
* Author              : WeeDo 
* History             : 16/02/2009 - Matheus Gonçalves - VERSÃO INICIAL
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_PERSONA' FROM DUAL;
drop table APPP_TB_PERSONA;


/

