/**********************************************************************************************************************
* Project Name         : SiGEPAPP
* APPP_TB_RESPOSTA.SQL : Script para drop da tabela APPP_TB_RESPOSTA
* Author               : WeeDo 
* History              : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a Sequence APPP_SEQ_RESPOSTA' FROM DUAL;
Drop sequence APPP_SEQ_RESPOSTA;

SELECT 'Dropando a tabela APPP_TB_RESPOSTA' FROM DUAL;
drop table APPP_TB_RESPOSTA;

 
/
