/**********************************************************************************************************************
* Project Name             : SiGEPAPP
* APPP_TB_ANTI_PATTERN.SQL : Script para drop da tabela APPP_TB_ANTI_PATTERN
* Author                   : WeeDo 
* History                  : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_ANTI_PATTERN' FROM DUAL;
drop table APPP_TB_ANTI_PATTERN;

/
