/**********************************************************************************************************************
* Project Name              : SiGEPAPP
* APPP_TB_USER_ENDERECO.SQL : Script para drop da tabela APPP_TB_USER_ENDERECO
* Author                    : WeeDo 
* History                   : 16/02/2009 - Matheus Gonçalves
***********************************************************************************************************************/

SELECT 'Dropando a tabela APPP_TB_USER_ENDERECO' FROM DUAL;
drop table APPP_TB_USER_ENDERECO;
/
